export const ko = {
    doLogIn: "로그인",
    doRegister: "회원가입",
    doRegisterSecurityKey: "보안 키 등록",
    doCancel: "취소",
    doSubmit: "제출",
    doBack: "뒤로",
    doYes: "예",
    doNo: "아니오",
    doContinue: "계속",
    doIgnore: "무시",
    doAccept: "수락",
    doDecline: "거절",
    doForgotPassword: "비밀번호를 잊으셨나요?",
    doClickHere: "여기를 클릭하세요",
    doImpersonate: "대리 로그인",
    doTryAgain: "다시 시도",
    doTryAnotherWay: "다른 방법으로 시도",
    doConfirmDelete: "삭제 확인",
    errorDeletingAccount: "계정을 삭제하는 동안 오류가 발생했습니다",
    deletingAccountForbidden: "계정을 삭제할 권한이 없습니다. 관리자에게 문의하세요.",
    kerberosNotConfigured: "Kerberos가 설정되지 않음",
    kerberosNotConfiguredTitle: "Kerberos가 설정되지 않음",
    bypassKerberosDetail:
        "Kerberos로 로그인하지 않았거나 브라우저가 Kerberos 로그인을 설정하지 않았습니다. 계속하려면 다른 방법으로 로그인하십시오.",
    kerberosNotSetUp: "Kerberos가 설정되지 않았습니다. 로그인할 수 없습니다.",
    registerTitle: "회원가입",
    loginAccountTitle: "계정에 로그인",
    loginTitle: "MEMOCODE | 로그인",
    loginTitleHtml: "MEMOCODE",
    impersonateTitle: "{0} 사용자 대리 로그인",
    impersonateTitleHtml: "<strong>{0}</strong> 사용자 대리 로그인",
    realmChoice: "영역",
    unknownUser: "알 수 없는 사용자",
    loginTotpTitle: "모바일 인증기 설정",
    loginProfileTitle: "계정 정보 업데이트",
    loginIdpReviewProfileTitle: "계정 정보 업데이트",
    loginTimeout:
        "로그인 시도가 시간 초과되었습니다. 로그인 절차를 처음부터 시작하십시오.",
    reauthenticate: "계속하려면 다시 인증하십시오",
    authenticateStrong: "계속하려면 강력한 인증이 필요합니다",
    oauthGrantTitle: "{0}에 대한 액세스 권한 부여",
    oauthGrantTitleHtml: "{0}",
    oauthGrantInformation:
        "{0}가 데이터를 처리하는 방법을 알아보고 {0}를 신뢰할 수 있는지 확인하십시오.",
    oauthGrantReview: "검토할 수 있습니다",
    oauthGrantTos: "서비스 약관.",
    oauthGrantPolicy: "개인정보 보호정책.",
    errorTitle: "죄송합니다...",
    errorTitleHtml: "죄송합니다...",
    emailVerifyTitle: "이메일 확인",
    emailForgotTitle: "비밀번호를 잊으셨나요?",
    updateEmailTitle: "이메일 업데이트",
    emailUpdateConfirmationSentTitle: "확인 이메일이 전송되었습니다",
    emailUpdateConfirmationSent:
        "{0}로 확인 이메일이 전송되었습니다. 이메일 업데이트를 완료하려면 지침을 따르십시오.",
    emailUpdatedTitle: "이메일 업데이트됨",
    emailUpdated: "계정 이메일이 성공적으로 {0}(으)로 업데이트되었습니다.",
    updatePasswordTitle: "비밀번호 업데이트",
    codeSuccessTitle: "성공 코드",
    codeErrorTitle: "오류 코드: {0}",
    displayUnsupported: "요청한 표시 유형을 지원하지 않습니다",
    browserRequired: "로그인하려면 브라우저가 필요합니다",
    browserContinue: "로그인을 완료하려면 브라우저가 필요합니다",
    browserContinuePrompt: "브라우저를 열고 로그인 절차를 계속하시겠습니까? [y/n]:",
    browserContinueAnswer: "y",
    usb: "USB",
    nfc: "NFC",
    bluetooth: "Bluetooth",
    internal: "내부",
    unknown: "알 수 없음",
    termsTitle: "이용 약관",
    termsText: "",
    termsPlainText: "이용 약관이 정의되어야 합니다.",
    termsAcceptanceRequired: "이용 약관에 동의해야 합니다.",
    acceptTerms: "이용 약관에 동의합니다",
    deleteCredentialTitle: "{0} 삭제",
    deleteCredentialMessage: "{0}를 삭제하시겠습니까?",
    recaptchaFailed: "잘못된 Recaptcha",
    recaptchaNotConfigured: "Recaptcha가 필요하지만 구성되지 않았습니다",
    consentDenied: "동의 거부됨.",
    noAccount: "새 사용자?",
    username: "사용자 이름",
    usernameOrEmail: "사용자 이름 또는 이메일",
    firstName: "이름",
    givenName: "이름",
    fullName: "전체 이름",
    lastName: "성",
    familyName: "성",
    email: "이메일",
    password: "비밀번호",
    passwordConfirm: "비밀번호 확인",
    passwordNew: "새 비밀번호",
    passwordNewConfirm: "새 비밀번호 확인",
    hidePassword: "비밀번호 숨기기",
    showPassword: "비밀번호 보기",
    rememberMe: "로그인 상태 유지",
    authenticatorCode: "일회용 코드",
    address: "주소",
    street: "거리",
    locality: "도시 또는 지역",
    region: "주, 도, 지역",
    postal_code: "우편 번호",
    country: "국가",
    emailVerified: "이메일 확인됨",
    website: "웹 페이지",
    phoneNumber: "전화 번호",
    phoneNumberVerified: "전화 번호 확인됨",
    gender: "성별",
    birthday: "생년월일",
    zoneinfo: "시간대",
    gssDelegationCredential: "GSS 위임 자격 증명",
    logoutOtherSessions: "다른 장치에서 로그아웃",
    profileScopeConsentText: "사용자 프로필",
    emailScopeConsentText: "이메일 주소",
    addressScopeConsentText: "주소",
    phoneScopeConsentText: "전화 번호",
    offlineAccessScopeConsentText: "오프라인 액세스",
    samlRoleListScopeConsentText: "내 역할",
    rolesScopeConsentText: "사용자 역할",
    restartLoginTooltip: "로그인 재시작",
    loginTotpIntro: "이 계정에 액세스하려면 일회용 비밀번호 생성기를 설정해야 합니다",
    loginTotpStep1: "다음 애플리케이션 중 하나를 모바일에 설치하십시오:",
    loginTotpStep2: "애플리케이션을 열고 바코드를 스캔하십시오:",
    loginTotpStep3:
        "애플리케이션에서 제공하는 일회용 코드를 입력하고 설정을 완료하려면 제출을 클릭하십시오.",
    loginTotpStep3DeviceName:
        "OTP 장치를 관리하는 데 도움이 되는 장치 이름을 입력하십시오.",
    loginTotpManualStep2: "애플리케이션을 열고 키를 입력하십시오:",
    loginTotpManualStep3:
        "애플리케이션에서 설정을 허용하는 경우 다음 구성 값을 사용하십시오:",
    loginTotpUnableToScan: "스캔할 수 없습니까?",
    loginTotpScanBarcode: "바코드 스캔?",
    loginCredential: "자격 증명",
    loginOtpOneTime: "일회용 코드",
    loginTotpType: "유형",
    loginTotpAlgorithm: "알고리즘",
    loginTotpDigits: "자릿수",
    loginTotpInterval: "간격",
    loginTotpCounter: "카운터",
    loginTotpDeviceName: "장치 이름",
    loginTotp: "시간 기반",
    loginHotp: "카운터 기반",
    totpAppFreeOTPName: "FreeOTP",
    totpAppGoogleName: "Google Authenticator",
    totpAppMicrosoftAuthenticatorName: "Microsoft Authenticator",
    loginChooseAuthenticator: "로그인 방법 선택",
    oauthGrantRequest: "이 액세스 권한을 부여하시겠습니까?",
    inResource: "에서",
    oauth2DeviceVerificationTitle: "장치 로그인",
    verifyOAuth2DeviceUserCode: "장치에서 제공된 코드를 입력하고 제출을 클릭하십시오",
    oauth2DeviceInvalidUserCodeMessage: "잘못된 코드입니다. 다시 시도하십시오.",
    oauth2DeviceExpiredUserCodeMessage:
        "코드가 만료되었습니다. 장치로 돌아가서 다시 연결하십시오.",
    oauth2DeviceVerificationCompleteHeader: "장치 로그인 성공",
    oauth2DeviceVerificationCompleteMessage: "이 브라우저 창을 닫고 장치로 돌아가십시오.",
    oauth2DeviceVerificationFailedHeader: "장치 로그인 실패",
    oauth2DeviceVerificationFailedMessage:
        "이 브라우저 창을 닫고 장치로 돌아가서 다시 연결을 시도하십시오.",
    oauth2DeviceConsentDeniedMessage: "장치를 연결하는 데 동의하지 않았습니다.",
    oauth2DeviceAuthorizationGrantDisabledMessage:
        "클라이언트가 OAuth 2.0 장치 승인 부여를 시작할 수 없습니다. 클라이언트에 대해 흐름이 비활성화되었습니다.",
    emailVerifyInstruction1:
        "이메일 주소 {0}로 이메일 확인 지침이 포함된 이메일이 전송되었습니다.",
    emailVerifyInstruction2: "이메일에서 확인 코드를 받지 못했습니까?",
    emailVerifyInstruction3: "이메일을 다시 전송하십시오.",
    emailLinkIdpTitle: "{0} 연결",
    emailLinkIdp1:
        "{0} 계정 {1}을(를) {2} 계정과 연결하는 방법에 대한 지침이 포함된 이메일이 전송되었습니다.",
    emailLinkIdp2: "이메일에서 확인 코드를 받지 못했습니까?",
    emailLinkIdp3: "이메일을 다시 전송하십시오.",
    emailLinkIdp4: "다른 브라우저에서 이미 이메일을 확인했습니까?",
    emailLinkIdp5: "계속하려면 여기를 클릭하십시오.",
    backToLogin: "&laquo; 로그인으로 돌아가기",
    emailInstruction:
        "사용자 이름 또는 이메일 주소를 입력하면 새 비밀번호를 생성하는 방법에 대한 지침이 전송됩니다.",
    emailInstructionUsername:
        "사용자 이름을 입력하면 새 비밀번호를 생성하는 방법에 대한 지침이 전송됩니다.",
    copyCodeInstruction: "이 코드를 복사하여 애플리케이션에 붙여 넣으십시오:",
    pageExpiredTitle: "페이지가 만료되었습니다",
    pageExpiredMsg1: "로그인 절차를 다시 시작하려면",
    pageExpiredMsg2: "로그인 절차를 계속하려면",
    personalInfo: "개인 정보:",
    role_admin: "관리자",
    role_realm_admin: "영역 관리자",
    role_create_realm: "영역 생성",
    role_create_client: "클라이언트 생성",
    role_view_realm: "영역 보기",
    role_view_users: "사용자 보기",
    role_view_applications: "애플리케이션 보기",
    role_view_clients: "클라이언트 보기",
    role_view_events: "이벤트 보기",
    role_view_identity_providers: "아이덴티티 제공자 보기",
    role_manage_realm: "영역 관리",
    role_manage_users: "사용자 관리",
    role_manage_applications: "애플리케이션 관리",
    role_manage_identity_providers: "아이덴티티 제공자 관리",
    role_manage_clients: "클라이언트 관리",
    role_manage_events: "이벤트 관리",
    role_view_profile: "프로필 보기",
    role_manage_account: "계정 관리",
    role_manage_account_links: "계정 링크 관리",
    role_read_token: "토큰 읽기",
    role_offline_access: "오프라인 접근",
    client_account: "계정",
    client_account_console: "계정 콘솔",
    client_security_admin_console: "보안 관리자 콘솔",
    client_admin_cli: "관리자 CLI",
    client_realm_management: "영역 관리",
    client_broker: "브로커",
    requiredFields: "필수 필드",
    invalidUserMessage: "잘못된 사용자 이름 또는 비밀번호.",
    invalidUsernameMessage: "잘못된 사용자 이름.",
    invalidUsernameOrEmailMessage: "잘못된 사용자 이름 또는 이메일.",
    invalidPasswordMessage: "잘못된 비밀번호.",
    invalidEmailMessage: "잘못된 이메일 주소.",
    accountDisabledMessage: "계정이 비활성화되었습니다. 관리자에게 문의하십시오.",
    accountTemporarilyDisabledMessage:
        "계정이 일시적으로 비활성화되었습니다. 관리자에게 문의하거나 나중에 다시 시도하십시오.",
    expiredCodeMessage: "로그인 시간 초과. 다시 로그인하십시오.",
    expiredActionMessage: "작업이 만료되었습니다. 지금 로그인 절차를 계속하십시오.",
    expiredActionTokenNoSessionMessage: "작업이 만료되었습니다.",
    expiredActionTokenSessionExistsMessage: "작업이 만료되었습니다. 다시 시작하십시오.",
    sessionLimitExceeded: "세션 수가 너무 많습니다",
    missingFirstNameMessage: "이름을 입력하십시오.",
    missingLastNameMessage: "성을 입력하십시오.",
    missingEmailMessage: "이메일을 입력하십시오.",
    missingUsernameMessage: "사용자 이름을 입력하십시오.",
    missingPasswordMessage: "비밀번호를 입력하십시오.",
    missingTotpMessage: "인증기 코드를 입력하십시오.",
    missingTotpDeviceNameMessage: "장치 이름을 입력하십시오.",
    notMatchPasswordMessage: "비밀번호가 일치하지 않습니다.",
    error_invalid_value: "잘못된 값.",
    error_invalid_blank: "값을 입력하십시오.",
    error_empty: "값을 입력하십시오.",
    error_invalid_length: "길이는 {1}에서 {2} 사이여야 합니다.",
    error_invalid_length_too_short: "최소 길이는 {1}입니다.",
    error_invalid_length_too_long: "최대 길이는 {2}입니다.",
    error_invalid_email: "잘못된 이메일 주소.",
    error_invalid_number: "잘못된 숫자.",
    error_number_out_of_range: "숫자는 {1}에서 {2} 사이여야 합니다.",
    error_number_out_of_range_too_small: "숫자는 최소 {1}이어야 합니다.",
    error_number_out_of_range_too_big: "숫자는 최대 {2}이어야 합니다.",
    error_pattern_no_match: "잘못된 값.",
    error_invalid_uri: "잘못된 URL.",
    error_invalid_uri_scheme: "잘못된 URL 스키마.",
    error_invalid_uri_fragment: "잘못된 URL 조각.",
    error_user_attribute_required: "이 필드를 입력하십시오.",
    error_invalid_date: "잘못된 날짜.",
    error_user_attribute_read_only: "이 필드는 읽기 전용입니다.",
    error_username_invalid_character: "값에 잘못된 문자가 포함되어 있습니다.",
    error_person_name_invalid_character: "값에 잘못된 문자가 포함되어 있습니다.",
    error_reset_otp_missing_id: "OTP 구성을 선택하십시오.",
    invalidPasswordExistingMessage: "잘못된 기존 비밀번호.",
    invalidPasswordBlacklistedMessage:
        "잘못된 비밀번호: 비밀번호가 블랙리스트에 있습니다.",
    invalidPasswordConfirmMessage: "비밀번호 확인이 일치하지 않습니다.",
    invalidTotpMessage: "잘못된 인증기 코드.",
    usernameExistsMessage: "사용자 이름이 이미 존재합니다.",
    emailExistsMessage: "이메일이 이미 존재합니다.",
    federatedIdentityExistsMessage:
        "{0} {1}을(를) 사용자가 이미 존재합니다. 계정 관리에 로그인하여 계정을 연결하십시오.",
    federatedIdentityUnavailableMessage:
        "아이덴티티 제공자 {1}의 사용자 {0}이(가) 존재하지 않습니다. 관리자에게 문의하십시오.",
    federatedIdentityUnmatchedEssentialClaimMessage:
        "아이덴티티 제공자가 발행한 ID 토큰이 구성된 필수 클레임과 일치하지 않습니다. 관리자에게 문의하십시오.",
    confirmLinkIdpTitle: "계정이 이미 존재합니다",
    federatedIdentityConfirmLinkMessage:
        "{0} {1}을(를) 사용자가 이미 존재합니다. 어떻게 계속하시겠습니까?",
    federatedIdentityConfirmReauthenticateMessage:
        "{0}과(와) 계정을 연결하려면 인증하십시오",
    nestedFirstBrokerFlowMessage:
        "{0} 사용자 {1}이(가) 알려진 사용자와 연결되지 않았습니다.",
    confirmLinkIdpReviewProfile: "프로필 검토",
    confirmLinkIdpContinue: "기존 계정에 추가",
    configureTotpMessage: "계정을 활성화하려면 모바일 인증기를 설정해야 합니다.",
    configureBackupCodesMessage: "계정을 활성화하려면 백업 코드를 설정해야 합니다.",
    updateProfileMessage: "계정을 활성화하려면 사용자 프로필을 업데이트해야 합니다.",
    updatePasswordMessage: "계정을 활성화하려면 비밀번호를 변경해야 합니다.",
    updateEmailMessage: "계정을 활성화하려면 이메일 주소를 업데이트해야 합니다.",
    resetPasswordMessage: "비밀번호를 변경해야 합니다.",
    verifyEmailMessage: "계정을 활성화하려면 이메일 주소를 확인해야 합니다.",
    linkIdpMessage: "{0}과(와) 계정을 연결하려면 이메일 주소를 확인해야 합니다.",
    emailSentMessage: "곧 이메일을 받게 될 것이며, 자세한 지침이 포함되어 있습니다.",
    emailSendErrorMessage: "이메일 전송에 실패했습니다. 나중에 다시 시도하십시오.",
    accountUpdatedMessage: "계정이 업데이트되었습니다.",
    accountPasswordUpdatedMessage: "비밀번호가 업데이트되었습니다.",
    delegationCompleteHeader: "로그인 성공",
    delegationCompleteMessage:
        "이 브라우저 창을 닫고 콘솔 애플리케이션으로 돌아가십시오.",
    delegationFailedHeader: "로그인 실패",
    delegationFailedMessage:
        "이 브라우저 창을 닫고 콘솔 애플리케이션으로 돌아가 다시 로그인하십시오.",
    noAccessMessage: "액세스 없음",
    invalidPasswordMinLengthMessage: "잘못된 비밀번호: 최소 길이 {0}.",
    invalidPasswordMaxLengthMessage: "잘못된 비밀번호: 최대 길이 {0}.",
    invalidPasswordMinDigitsMessage:
        "잘못된 비밀번호: 최소 {0}개의 숫자가 포함되어야 합니다.",
    invalidPasswordMinLowerCaseCharsMessage:
        "잘못된 비밀번호: 최소 {0}개의 소문자가 포함되어야 합니다.",
    invalidPasswordMinUpperCaseCharsMessage:
        "잘못된 비밀번호: 최소 {0}개의 대문자가 포함되어야 합니다.",
    invalidPasswordMinSpecialCharsMessage:
        "잘못된 비밀번호: 최소 {0}개의 특수 문자가 포함되어야 합니다.",
    invalidPasswordNotUsernameMessage:
        "잘못된 비밀번호: 사용자 이름과 일치해서는 안 됩니다.",
    invalidPasswordNotEmailMessage: "잘못된 비밀번호: 이메일과 일치해서는 안 됩니다.",
    invalidPasswordRegexPatternMessage:
        "잘못된 비밀번호: 정규 표현식 패턴과 일치하지 않습니다.",
    invalidPasswordHistoryMessage:
        "잘못된 비밀번호: 최근 {0}개의 비밀번호와 일치해서는 안 됩니다.",
    invalidPasswordGenericMessage:
        "잘못된 비밀번호: 새 비밀번호가 비밀번호 정책과 일치하지 않습니다.",
    failedToProcessResponseMessage: "응답을 처리하지 못했습니다",
    httpsRequiredMessage: "HTTPS가 필요합니다",
    realmNotEnabledMessage: "영역이 활성화되지 않았습니다",
    invalidRequestMessage: "잘못된 요청",
    successLogout: "로그아웃되었습니다",
    failedLogout: "로그아웃 실패",
    unknownLoginRequesterMessage: "알 수 없는 로그인 요청자",
    loginRequesterNotEnabledMessage: "로그인 요청자가 활성화되지 않았습니다",
    bearerOnlyMessage: "Bearer-only 애플리케이션은 브라우저 로그인을 시작할 수 없습니다",
    standardFlowDisabledMessage:
        "클라이언트가 주어진 응답 유형으로 브라우저 로그인을 시작할 수 없습니다. 표준 흐름이 클라이언트에 대해 비활성화되었습니다.",
    implicitFlowDisabledMessage:
        "클라이언트가 주어진 응답 유형으로 브라우저 로그인을 시작할 수 없습니다. 암시적 흐름이 클라이언트에 대해 비활성화되었습니다.",
    invalidRedirectUriMessage: "잘못된 리디렉션 URI",
    unsupportedNameIdFormatMessage: "지원되지 않는 NameIDFormat",
    invalidRequesterMessage: "잘못된 요청자",
    registrationNotAllowedMessage: "등록이 허용되지 않음",
    resetCredentialNotAllowedMessage: "자격 증명 재설정이 허용되지 않음",
    permissionNotApprovedMessage: "권한이 승인되지 않았습니다.",
    noRelayStateInResponseMessage:
        "아이덴티티 제공자로부터의 응답에 릴레이 상태가 없습니다.",
    insufficientPermissionMessage: "아이덴티티를 연결할 권한이 부족합니다.",
    couldNotProceedWithAuthenticationRequestMessage:
        "아이덴티티 제공자에게 인증 요청을 진행할 수 없습니다.",
    couldNotObtainTokenMessage: "아이덴티티 제공자로부터 토큰을 받을 수 없습니다.",
    unexpectedErrorRetrievingTokenMessage:
        "아이덴티티 제공자로부터 토큰을 받을 때 예기치 않은 오류가 발생했습니다.",
    unexpectedErrorHandlingResponseMessage:
        "아이덴티티 제공자로부터의 응답을 처리할 때 예기치 않은 오류가 발생했습니다.",
    identityProviderAuthenticationFailedMessage:
        "아이덴티티 제공자와의 인증에 실패했습니다. 인증할 수 없습니다.",
    couldNotSendAuthenticationRequestMessage:
        "아이덴티티 제공자에게 인증 요청을 보낼 수 없습니다.",
    unexpectedErrorHandlingRequestMessage:
        "아이덴티티 제공자에게 인증 요청을 처리할 때 예기치 않은 오류가 발생했습니다.",
    invalidAccessCodeMessage: "잘못된 접근 코드.",
    sessionNotActiveMessage: "세션이 활성 상태가 아닙니다.",
    invalidCodeMessage: "오류가 발생했습니다. 애플리케이션을 통해 다시 로그인하십시오.",
    cookieNotFoundMessage:
        "쿠키를 찾을 수 없습니다. 브라우저에서 쿠키가 활성화되어 있는지 확인하십시오.",
    insufficientLevelOfAuthentication: "요청된 인증 수준이 충족되지 않았습니다.",
    identityProviderUnexpectedErrorMessage:
        "아이덴티티 제공자와의 인증 중 예기치 않은 오류가 발생했습니다",
    identityProviderMissingStateMessage:
        "아이덴티티 제공자로부터의 응답에 상태 매개변수가 누락되었습니다.",
    identityProviderMissingCodeOrErrorMessage:
        "아이덴티티 제공자로부터의 응답에 코드 또는 오류 매개변수가 누락되었습니다.",
    identityProviderInvalidResponseMessage: "아이덴티티 제공자로부터 잘못된 응답.",
    identityProviderInvalidSignatureMessage:
        "아이덴티티 제공자로부터의 응답에 잘못된 서명.",
    identityProviderNotFoundMessage:
        "식별자와 일치하는 아이덴티티 제공자를 찾을 수 없습니다.",
    identityProviderLinkSuccess:
        "이메일을 성공적으로 확인했습니다. 원래 브라우저로 돌아가서 로그인 절차를 계속하십시오.",
    staleCodeMessage:
        "이 페이지는 더 이상 유효하지 않습니다. 애플리케이션으로 돌아가서 다시 로그인하십시오",
    realmSupportsNoCredentialsMessage: "영역이 자격 증명 유형을 지원하지 않습니다.",
    credentialSetupRequired: "로그인할 수 없습니다. 자격 증명 설정이 필요합니다.",
    identityProviderNotUniqueMessage:
        "영역이 여러 아이덴티티 제공자를 지원합니다. 어떤 아이덴티티 제공자를 사용하여 인증해야 할지 알 수 없습니다.",
    emailVerifiedMessage: "이메일 주소가 확인되었습니다.",
    emailVerifiedAlreadyMessage: "이메일 주소가 이미 확인되었습니다.",
    staleEmailVerificationLink:
        "클릭한 링크는 오래된 링크로 더 이상 유효하지 않습니다. 이메일을 이미 확인했을 수 있습니다.",
    identityProviderAlreadyLinkedMessage:
        "{0}에서 반환된 연동된 아이덴티티가 이미 다른 사용자와 연결되어 있습니다.",
    confirmAccountLinking:
        "{0} 아이덴티티 제공자의 계정 {1}을(를) 자신의 계정과 연결하는 것을 확인하십시오.",
    confirmEmailAddressVerification: "이메일 주소 {0}의 유효성을 확인하십시오.",
    confirmExecutionOfActions: "다음 작업을 수행하십시오",
    locale_ar: "عربي",
    locale_ca: "Català",
    locale_cs: "Čeština",
    locale_da: "Dansk",
    locale_de: "Deutsch",
    locale_en: "English",
    locale_es: "Español",
    locale_fi: "Suomi",
    locale_fr: "Français",
    locale_hu: "Magyar",
    locale_it: "Italiano",
    locale_ja: "日本語",
    locale_lt: "Lietuvių",
    locale_lv: "Latviešu",
    locale_nl: "Nederlands",
    locale_no: "한국어",
    locale_pl: "Polski",
    locale_pt_BR: "Português (Brasil)",
    locale_ru: "Русский",
    locale_sk: "Slovenčina",
    locale_sv: "Svenska",
    locale_th: "ไทย",
    locale_tr: "Türkçe",
    locale_uk: "Українська",
    locale_zh_CN: "中文简体",
    backToApplication: "&laquo; 애플리케이션으로 돌아가기",
    missingParameterMessage: "누락된 매개변수: {0}",
    clientNotFoundMessage: "클라이언트를 찾을 수 없습니다.",
    clientDisabledMessage: "클라이언트가 비활성화되었습니다.",
    invalidParameterMessage: "잘못된 매개변수: {0}",
    alreadyLoggedIn: "이미 로그인되어 있습니다.",
    differentUserAuthenticated:
        "현재 세션에서 다른 사용자 '{0}'로 이미 인증되었습니다. 먼저 로그아웃하십시오.",
    brokerLinkingSessionExpired:
        "브로커 계정 연결을 요청했지만 현재 세션이 더 이상 유효하지 않습니다.",
    proceedWithAction: "&raquo; 계속하려면 여기를 클릭하십시오",
    acrNotFulfilled: "인증 요구 사항이 충족되지 않았습니다",
    requiredAction_CONFIGURE_TOTP: "OTP 구성",
    requiredAction_TERMS_AND_CONDITIONS: "이용 약관",
    requiredAction_UPDATE_PASSWORD: "비밀번호 업데이트",
    requiredAction_UPDATE_PROFILE: "프로필 업데이트",
    requiredAction_VERIFY_EMAIL: "이메일 확인",
    requiredAction_CONFIGURE_RECOVERY_AUTHN_CODES: "복구 코드 생성",
    requiredAction_webauthn_register_passwordless: "비밀번호 없는 Webauthn 등록",
    invalidTokenRequiredActions: "링크에 포함된 필수 작업이 유효하지 않습니다",
    doX509Login: "다음 사용자로 로그인됩니다:",
    clientCertificate: "X509 클라이언트 인증서:",
    noCertificate: "[인증서 없음]",
    pageNotFound: "페이지를 찾을 수 없습니다",
    internalServerError: "내부 서버 오류가 발생했습니다",
    console_username: "사용자 이름:",
    console_password: "비밀번호:",
    console_otp: "일회용 비밀번호:",
    console_new_password: "새 비밀번호:",
    console_confirm_password: "비밀번호 확인:",
    console_update_password: "비밀번호 업데이트가 필요합니다.",
    console_verify_email:
        "이메일 주소를 확인해야 합니다. {0}로 확인 코드가 포함된 이메일을 보냈습니다. 아래 입력란에 이 코드를 입력하십시오.",
    console_email_code: "이메일 코드:",
    console_accept_terms: "이용 약관에 동의하시겠습니까? [y/n]:",
    console_accept: "y",
    openshift_scope_user_info: "사용자 정보",
    openshift_scope_user_check_access: "사용자 접근 정보",
    openshift_scope_user_full: "전체 접근",
    openshift_scope_list_projects: "프로젝트 목록",
    saml_post_form_title: "인증 리디렉션",
    saml_post_form_message: "리디렉션 중입니다. 잠시만 기다려 주십시오.",
    saml_post_form_js_disabled:
        "JavaScript가 비활성화되었습니다. 활성화하는 것이 좋습니다. 계속하려면 아래 버튼을 클릭하십시오.",
    saml_artifact_resolution_service_invalid_response: "아티팩트를 해결할 수 없습니다.",
    otp_display_name: "인증 애플리케이션",
    otp_help_text: "인증 애플리케이션에서 확인 코드를 입력하십시오.",
    otp_reset_description: "어떤 OTP 구성을 제거하시겠습니까?",
    password_display_name: "비밀번호",
    password_help_text: "비밀번호를 입력하여 로그인하십시오.",
    auth_username_form_display_name: "사용자 이름",
    auth_username_form_help_text: "사용자 이름을 입력하여 로그인 절차를 시작하십시오",
    auth_username_password_form_display_name: "사용자 이름 및 비밀번호",
    auth_username_password_form_help_text:
        "사용자 이름과 비밀번호를 입력하여 로그인하십시오.",
    auth_recovery_authn_code_form_display_name: "복구 인증 코드",
    auth_recovery_authn_code_form_help_text:
        "이전에 생성된 목록에서 복구 인증 코드를 입력하십시오.",
    auth_recovery_code_info_message: "지정된 복구 코드를 입력하십시오.",
    auth_recovery_code_prompt: "복구 코드 #{0}",
    auth_recovery_code_header: "복구 인증 코드로 로그인",
    recovery_codes_error_invalid: "잘못된 복구 인증 코드",
    recovery_code_config_header: "복구 인증 코드",
    recovery_code_config_warning_title:
        "이 페이지를 나간 후에는 이 복구 코드를 다시 볼 수 없습니다",
    recovery_code_config_warning_message:
        "프린트하거나 다운로드하거나 암호 관리자로 복사하여 안전하게 보관하십시오. 이 설정을 취소하면 계정에서 이 복구 코드가 제거됩니다.",
    recovery_codes_print: "프린트",
    recovery_codes_download: "다운로드",
    recovery_codes_copy: "복사",
    recovery_codes_copied: "복사됨",
    recovery_codes_confirmation_message: "이 코드를 안전한 곳에 보관했습니다",
    recovery_codes_action_complete: "설정 완료",
    recovery_codes_action_cancel: "설정 취소",
    recovery_codes_download_file_header: "이 복구 코드를 안전한 곳에 보관하십시오.",
    recovery_codes_download_file_description:
        "복구 코드는 인증기에 접근할 수 없을 때 계정에 로그인할 수 있는 일회용 패스코드입니다.",
    recovery_codes_download_file_date: "이 코드는 생성되었습니다",
    recovery_codes_label_default: "복구 코드",
    webauthn_display_name: "비밀번호 키",
    webauthn_help_text: "비밀번호 키를 사용하여 로그인하십시오.",
    webauthn_passwordless_display_name: "비밀번호 없는 비밀번호 키",
    webauthn_passwordless_help_text:
        "비밀번호 없는 비밀번호 키를 사용하여 로그인하십시오.",
    webauthn_login_title: "비밀번호 키 로그인",
    webauthn_registration_title: "비밀번호 키 등록",
    webauthn_available_authenticators: "사용 가능한 비밀번호 키",
    webauthn_unsupported_browser_text:
        "이 브라우저에서는 WebAuthn이 지원되지 않습니다. 다른 브라우저를 사용하거나 관리자에게 문의하십시오.",
    webauthn_doAuthenticate: "비밀번호 키로 로그인",
    webauthn_createdAt_label: "생성됨",
    webauthn_error_title: "비밀번호 키 오류",
    webauthn_error_registration: "비밀번호 키 등록에 실패했습니다.<br/> {0}",
    webauthn_error_api_get: "비밀번호 키 인증에 실패했습니다.<br/> {0}",
    webauthn_error_different_user:
        "첫 번째 인증된 사용자가 비밀번호 키로 인증된 사용자가 아닙니다.",
    webauthn_error_auth_verification:
        "비밀번호 키 인증 결과가 유효하지 않습니다.<br/> {0}",
    webauthn_error_register_verification:
        "비밀번호 키 등록 결과가 유효하지 않습니다.<br/> {0}",
    webauthn_error_user_not_found: "비밀번호 키로 인증된 알 수 없는 사용자.",
    identity_provider_redirector: "다른 아이덴티티 제공자와 연결",
    identity_provider_login_label: "또는 다음으로 로그인",
    idp_email_verification_display_name: "이메일 확인",
    idp_email_verification_help_text: "이메일을 확인하여 계정을 연결하십시오.",
    idp_username_password_form_display_name: "사용자 이름 및 비밀번호",
    idp_username_password_form_help_text: "로그인하여 계정을 연결하십시오.",
    finalDeletionConfirmation:
        "계정을 삭제하면 복구할 수 없습니다. 계정을 유지하려면 취소를 클릭하십시오.",
    irreversibleAction: "이 작업은 되돌릴 수 없습니다",
    deleteAccountConfirm: "계정 삭제 확인",
    deletingImplies: "계정을 삭제하면 다음을 의미합니다:",
    errasingData: "모든 데이터 삭제",
    loggingOutImmediately: "즉시 로그아웃",
    accountUnusable: "이 계정으로 애플리케이션을 다시 사용할 수 없습니다",
    userDeletedSuccessfully: "사용자가 성공적으로 삭제되었습니다",
    access_denied: "접근 거부",
    access_denied_when_idp_auth: "{0}와 인증하는 동안 접근이 거부되었습니다",
    frontchannel_logout_title: "로그아웃 중",
    frontchannel_logout_message: "다음 앱에서 로그아웃 중입니다",
    logoutConfirmTitle: "로그아웃",
    logoutConfirmHeader: "로그아웃하시겠습니까?",
    doLogout: "로그아웃",
    readOnlyUsernameMessage: "사용자 이름을 업데이트할 수 없습니다. 읽기 전용입니다.",
    error_invalid_multivalued_size:
        "속성 {0}은(는) 최소 {1}개, 최대 {2}개의 값을 가져야 합니다.",
    shouldBeEqual: "{0}은(는) {1}과(와) 같아야 합니다",
    shouldBeDifferent: "{0}은(는) {1}과(와) 달라야 합니다",
    shouldMatchPattern: "패턴은 `/{0}/`과(와) 일치해야 합니다",
    mustBeAnInteger: "정수여야 합니다",
    notAValidOption: "유효한 옵션이 아닙니다",
    selectAnOption: "옵션을 선택하십시오",
    remove: "제거",
    addValue: "값 추가",
    languages: "언어"
};
